spring:
    profiles:
        active:
        - dev
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://klm1.com:7001/eureka/
  instance:
    instance-id: dept-8001.com

info:
  app.name: microservicecloud
  company.name: xxxx
  build.artifactId: $project.artifactId$
  build.version: $project.version$
        
    
            
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://klm1.com:7001/eureka/
  instance:
    instance-id: dept-8001.com

info:
  app.name: microservicecloud
  company.name: xxxx
  build.artifactId: $project.artifactId$
  build.version: $project.version$