spring:
    profiles:
        active:
        - dev
---
server:
    port: 8001

spring:
    profiles: dev
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidSource
        driver-class-name: org.gjt.mm.mysql.Dirver
        url: jdbc:mysql://localhost:3306/clouddb01
        username: root
        password: root
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-millis: 200
            
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.atguigu.springcloud.entities
    mapper-locations: 
    - classpath: mybatis/mapper/**/*.xml
eureka: 
    client:
        server-url:
            defaultZone: http://klm1.com:7001/eureka/
    instance:
        instance-id: dept-8001.com
        
    
            
---
server:
    port: 8001

spring:
    profiles: test
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidSource
        driver-class-name: org.gjt.mm.mysql.Dirver
        url: jdbc:mysql://localhost:3306/clouddb02
        username: root
        password: root
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-millis: 200
            
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.atguigu.springcloud.entities
    mapper-locations: 
    - classpath: mybatis/mapper/**/*.xml
eureka: 
    client:
        server-url:
            defaultZone: http://klm1.com:7001/eureka/
    instance:
        instance-id: dept-8001.com            
            